=== apple/ccs-calendarserver/conf/auth/accounts.dtd
<!--
Copyright (c) 2006-2015 Apple Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

<!ELEMENT directory (record*) >
  <!ATTLIST directory realm CDATA "">

  <!ELEMENT record (uid, guid?, short-name*, password?, full-name*, email*, member-uid*,
  					capacity?, floor?, associated-address?, abbreviated-name?, street-address?, geographic-location?)>
    <!ATTLIST record type (user|group|location|resource|address) "user">

    <!ELEMENT uid                 (#PCDATA)>
    <!ELEMENT guid                (#PCDATA)>
    <!ELEMENT password            (#PCDATA)>
    <!ELEMENT short-name          (#PCDATA)>
    <!ELEMENT full-name           (#PCDATA)>
    <!ELEMENT email               (#PCDATA)>
    <!ELEMENT member-uid          (#PCDATA)>
    <!ELEMENT capacity            (#PCDATA)>
    <!ELEMENT floor               (#PCDATA)>
    <!ELEMENT associated-address  (#PCDATA)>
    <!ELEMENT abbreviated-name    (#PCDATA)>
    <!ELEMENT street-address      (#PCDATA)>
    <!ELEMENT geographic-location (#PCDATA)>

=== apple/ccs-calendarserver/twistedcaldav/directory/test/accounts.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
Copyright (c) 2006-2014 Apple Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 -->

<!DOCTYPE accounts SYSTEM "../../../conf/auth/accounts.dtd">

<directory realm="Test">
  <record type="user">
    <short-name>admin</short-name>
    <uid>D11F03A0-97EA-48AF-9A6C-FAC7F3975766</uid>
    <password>nimda</password>
    <full-name>Administrators</full-name>
  </record>
  <record type="user">
    <short-name>wsanchez</short-name>
    <uid>6423F94A-6B76-4A3A-815B-D52CFD77935D</uid>
    <password>zehcnasw</password>
    <full-name>Wilfredo Sanchez</full-name>
    <email>wsanchez@example.com</email>
  </record>
  <record type="user">
    <short-name>cdaboo</short-name>
    <uid>5A985493-EE2C-4665-94CF-4DFEA3A89500</uid>
    <password>oobadc</password>
    <full-name>Cyrus Daboo</full-name>
    <email>cdaboo@example.com</email>
  </record>
  <record type="user">
    <short-name>lecroy</short-name>
    <uid>8B4288F6-CC82-491D-8EF9-642EF4F3E7D0</uid>
    <password>yorcel</password>
    <full-name>Chris Lecroy</full-name>
    <email>lecroy@example.com</email>
  </record>
  <record type="user">
    <short-name>dreid</short-name>
    <uid>5FF60DAD-0BDE-4508-8C77-15F0CA5C8DD1</uid>
    <password>dierd</password>
    <full-name>David Reid</full-name>
    <email>dreid@example.com</email>
  </record>
  <record type="user">
    <short-name>doublequotes</short-name>
    <uid>8E04787E-336D-41ED-A70B-D233AD0DCE6F</uid>
    <password>setouqelbuod</password>
    <full-name>Double "quotey" Quotes</full-name>
    <email>doublequotes@example.com</email>
  </record>
  <record type="user">
    <short-name>nocalendar</short-name>
    <uid>543D28BA-F74F-4D5F-9243-B3E3A61171E5</uid>
    <password>radnelacon</password>
    <full-name>No Calendar</full-name>
    <email>nocalendar@example.com</email>
  </record>
  <record type="user">
    <short-name>usera</short-name>
    <uid>7423F94A-6B76-4A3A-815B-D52CFD77935D</uid>
    <password>a</password>
    <full-name>a</full-name>
    <email>a@example.com</email>
  </record>
  <record type="user">
    <short-name>userb</short-name>
    <uid>8A985493-EE2C-4665-94CF-4DFEA3A89500</uid>
    <password>b</password>
    <full-name>b</full-name>
    <email>b@example.com</email>
  </record>
  <record type="user">
    <short-name>userc</short-name>
    <uid>9FF60DAD-0BDE-4508-8C77-15F0CA5C8DD2</uid>
    <password>c</password>
    <full-name>c</full-name>
    <email>c@example.com</email>
  </record>
  <record type="user">
    <short-name>usercalonly</short-name>
    <uid>9E1FFAC4-3CCD-45A1-8272-D161C92D2EEE</uid>
    <password>a</password>
    <full-name>a calonly</full-name>
    <email>a-calonly@example.com</email>
  </record>
  <record type="user">
    <short-name>useradbkonly</short-name>
    <uid>7678EC8A-A069-4E82-9066-7279C6718507</uid>
    <password>a</password>
    <full-name>a adbkonly</full-name>
    <email>a-adbkonly@example.com</email>
  </record>
  <record type="user">
    <short-name>nonascii</short-name>
    <short-name>nonascii佐藤</short-name>
    <uid>320B73A1-46E2-4180-9563-782DFDBE1F63</uid>
    <password>a</password>
    <full-name>佐藤佐藤佐藤</full-name>
    <email>nonascii@example.com</email>
  </record>
  <record type="user">
    <short-name>delegator</short-name>
    <uid>FC465590-E9E9-4746-ACE8-6C756A49FE4D</uid>
    <password>a</password>
    <full-name>Calendar Delegator</full-name>
    <email>calendardelegator@example.com</email>
  </record>
  <record type="user">
    <short-name>occasionaldelegate</short-name>
    <uid>EC465590-E9E9-4746-ACE8-6C756A49FE4D</uid>
    <password>a</password>
    <full-name>Occasional Delegate</full-name>
    <email>occasional@example.com</email>
  </record>
    <record type="user">
    <short-name>delegateviagroup</short-name>
    <uid>46D9D716-CBEE-490F-907A-66FA6C3767FF</uid>
    <password>a</password>
    <full-name>Delegate Via Group</full-name>
    <email>delegateviagroup@example.com</email>
  </record>
  <record type="group">
    <short-name>delegategroup</short-name>
    <uid>00599DAF-3E75-42DD-9DB7-52617E79943F</uid>
    <full-name>Delegate Group</full-name>
    <member-uid>delegateviagroup</member-uid>
  </record>

  <record type="user">
    <short-name>user01</short-name>
    <uid>user01</uid>
    <password>user01</password>
    <full-name>User 01</full-name>
    <email>user01@example.com</email>
  </record>

  <record type="user">
    <short-name>user02</short-name>
    <uid>user02</uid>
    <password>user02</password>
    <full-name>User 02</full-name>
    <email>user02@example.com</email>
  </record>

  <record type="user">
    <short-name>user03</short-name>
    <uid>user03</uid>
    <password>user03</password>
    <full-name>User 03</full-name>
    <email>user03@example.com</email>
  </record>

  <record type="user">
    <short-name>user04</short-name>
    <uid>user04</uid>
    <password>user04</password>
    <full-name>User 04</full-name>
    <email>user04@example.com</email>
  </record>

  <!-- Repeat is not (yet?) supported in twext.who.xml
  <user repeat="100">
    <short-name>user%02d</short-name>
    <uid>user%02d</uid>
    <password>%02duser</password>
    <full-name>~35 User %02d</full-name>
    <first-name>~5</first-name>
    <last-name>~9 User %02d</last-name>
    <email>~10@example.com</email>
  </user>
  -->

  <record type="group">
    <short-name>managers</short-name>
    <uid>9FF60DAD-0BDE-4508-8C77-15F0CA5C8DD1</uid>
    <password>managers</password>
    <full-name>Managers</full-name>
      <member-uid>lecroy</member-uid>
  </record>
  <record type="group">
    <short-name>admin</short-name>
    <uid>admin</uid>
    <password>admin</password>
    <full-name>Administrators</full-name>
      <member-uid>managers</member-uid>
  </record>
  <record type="group">
    <short-name>grunts</short-name>
    <uid>grunts</uid>
    <password>grunts</password>
    <full-name>We do all the work</full-name>
      <member-uid>wsanchez</member-uid>
      <member-uid>cdaboo</member-uid>
      <member-uid>dreid</member-uid>
  </record>
  <record type="group">
    <short-name>right_coast</short-name>
    <uid>right_coast</uid>
    <password>right_coast</password>
    <full-name>East Coast</full-name>
      <member-uid>cdaboo</member-uid>
  </record>
  <record type="group">
    <short-name>left_coast</short-name>
    <uid>left_coast</uid>
    <password>left_coast</password>
    <full-name>West Coast</full-name>
      <member-uid>wsanchez</member-uid>
      <member-uid>lecroy</member-uid>
      <member-uid>dreid</member-uid>
  </record>
  <record type="group">
    <short-name>both_coasts</short-name>
    <uid>both_coasts</uid>
    <password>both_coasts</password>
    <full-name>Both Coasts</full-name>
      <member-uid>right_coast</member-uid>
      <member-uid>left_coast</member-uid>
  </record>
  <record type="group">
    <short-name>recursive1_coasts</short-name>
    <uid>recursive1_coasts</uid>
    <password>recursive1_coasts</password>
    <full-name>Recursive1 Coasts</full-name>
      <member-uid>recursive2_coasts</member-uid>
      <member-uid>wsanchez</member-uid>
  </record>
  <record type="group">
    <short-name>recursive2_coasts</short-name>
    <uid>recursive2_coasts</uid>
    <password>recursive2_coasts</password>
    <full-name>Recursive2 Coasts</full-name>
      <member-uid>recursive1_coasts</member-uid>
      <member-uid>cdaboo</member-uid>
  </record>
  <record type="group">
    <short-name>non_calendar_group</short-name>
    <uid>non_calendar_group</uid>
    <password>non_calendar_group</password>
    <full-name>Non-calendar group</full-name>
      <member-uid>cdaboo</member-uid>
      <member-uid>lecroy</member-uid>
  </record>
  <!--
  <location>
    <uid>mercury</uid>
    <uid>mercury</uid>
    <password>mercury</password>
    <name>Mercury Seven</name>
    <email-address>mercury@example.com</email-address>
  </location>
  <location>
    <uid>gemini</uid>
    <uid>gemini</uid>
    <password>gemini</password>
    <name>Gemini Twelve</name>
    <email-address>gemini@example.com</email-address>
  </location>
  <location>
    <uid>apollo</uid>
    <uid>apollo</uid>
    <password>apollo</password>
    <name>Apollo Eleven</name>
    <email-address>apollo@example.com</email-address>
  </location>
  <location>
    <uid>orion</uid>
    <uid>orion</uid>
    <password>orion</password>
    <name>Orion</name>
    <email-address>orion@example.com</email-address>
  </location>
  <resource>
    <uid>transporter</uid>
    <uid>transporter</uid>
    <password>transporter</password>
    <name>Mass Transporter</name>
    <email-address>transporter@example.com</email-address>
  </resource>
  <resource>
    <uid>ftlcpu</uid>
    <uid>ftlcpu</uid>
    <password>ftlcpu</password>
    <name>Faster-Than-Light Microprocessor</name>
    <email-address>ftlcpu@example.com</email-address>
  </resource>
  <resource>
    <uid>non_calendar_proxy</uid>
    <uid>non_calendar_proxy</uid>
    <password>non_calendar_proxy</password>
    <name>Non-calendar proxy</name>
    <email-address>non_calendar_proxy@example.com</email-address>
  </resource>
  <resource>
    <uid>disabled</uid>
    <uid>disabled</uid>
    <password>disabled</password>
    <name>Disabled Record</name>
    <email-address>disabled@example.com</email-address>
  </resource>
-->
</directory>

=== apple/ccs-calendarserver/txdav/caldav/datastore/test/accounts/groupAttendeeAccounts.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
Copyright (c) 2006-2014 Apple Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 -->

<!DOCTYPE accounts SYSTEM "accounts.dtd">

<directory realm="Test Realm">
	<record type="user">
	    <short-name>user01</short-name>
	    <uid>user01</uid>
	    <guid>10000000-0000-0000-0000-000000000001</guid>
	    <password>user01</password>
	    <full-name>User 01</full-name>
	    <email>user01@example.com</email>
	</record>
	<record type="user">
	    <short-name>user02</short-name>
	    <uid>user02</uid>
	    <guid>10000000-0000-0000-0000-000000000002</guid>
	    <password>user02</password>
	    <full-name>User 02</full-name>
	    <email>user02@example.com</email>
	</record>
	<record type="user">
	    <short-name>user03</short-name>
	    <uid>user03</uid>
	    <guid>10000000-0000-0000-0000-000000000003</guid>
	    <password>user03</password>
	    <full-name>User 03</full-name>
	    <email>user03@example.com</email>
	</record>
	<record type="user">
	    <short-name>user04</short-name>
	    <uid>user04</uid>
	    <guid>10000000-0000-0000-0000-000000000004</guid>
	    <password>user04</password>
	    <full-name>User 04</full-name>
	    <email>user04@example.com</email>
	</record>
	<record type="user">
	    <short-name>user05</short-name>
	    <uid>user05</uid>
	    <guid>10000000-0000-0000-0000-000000000005</guid>
	    <password>user05</password>
	    <full-name>User 05</full-name>
	    <email>user05@example.com</email>
	</record>
	<record type="user">
	    <short-name>user06</short-name>
	    <uid>user06</uid>
	    <guid>10000000-0000-0000-0000-000000000006</guid>
	    <password>user06</password>
	    <full-name>User 06</full-name>
	    <email>user06@example.com</email>
	</record>
	<record type="user">
	    <short-name>user07</short-name>
	    <uid>user07</uid>
	    <guid>10000000-0000-0000-0000-000000000007</guid>
	    <password>user07</password>
	    <full-name>User 07</full-name>
	    <email>user07@example.com</email>
	</record>
	<record type="user">
	    <short-name>user08</short-name>
	    <uid>user08</uid>
	    <guid>10000000-0000-0000-0000-000000000008</guid>
	    <password>user08</password>
	    <full-name>User 08</full-name>
	    <email>user08@example.com</email>
	</record>
	<record type="user">
	    <short-name>user09</short-name>
	    <uid>user09</uid>
	    <guid>10000000-0000-0000-0000-000000000009</guid>
	    <password>user09</password>
	    <full-name>User 09</full-name>
	    <email>user09@example.com</email>
	</record>
	<record type="user">
	    <short-name>user10</short-name>
	    <uid>user10</uid>
	    <guid>10000000-0000-0000-0000-000000000010</guid>
	    <password>user10</password>
	    <full-name>User 10</full-name>
	    <email>user10@example.com</email>
	</record>
	<record type="group">
	    <short-name>group01</short-name>
	    <uid>group01</uid>
	    <guid>20000000-0000-0000-0000-000000000001</guid>
	    <full-name>Group 01</full-name>
	    <email>group01@example.com</email>
	    <member-uid>user02</member-uid>
	</record>
	<record type="group">
	    <short-name>group02</short-name>
	    <uid>group02</uid>
	    <guid>20000000-0000-0000-0000-000000000002</guid>
	    <full-name>Group 02</full-name>
	    <email>group02@example.com</email>
	    <member-uid>user06</member-uid>
	    <member-uid>user07</member-uid>
	    <member-uid>user08</member-uid>
	</record>
	<record type="group">
	    <short-name>group03</short-name>
	    <uid>group03</uid>
	    <guid>20000000-0000-0000-0000-000000000003</guid>
	    <full-name>Group 03</full-name>
	    <email>group03@example.com</email>
	    <member-uid>user07</member-uid>
	    <member-uid>user08</member-uid>
	    <member-uid>user09</member-uid>
	</record>
	<record type="group">
	    <short-name>group04</short-name>
	    <uid>group04</uid>
	    <guid>20000000-0000-0000-0000-000000000004</guid>
	    <full-name>Group 04</full-name>
	    <member-uid>group02</member-uid>
	    <member-uid>group03</member-uid>
	    <member-uid>user10</member-uid>
	</record>
</directory>

=== apple/ccs-calendarserver/twistedcaldav/directory/test/resources.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
Copyright (c) 2006-2014 Apple Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 -->

<!DOCTYPE accounts SYSTEM "../../../conf/auth/accounts.dtd">

<directory realm="Test">
  <record type="location">
    <uid>mercury</uid>
    <short-name>mercury</short-name>
    <password>mercury</password>
    <full-name>Mercury Seven</full-name>
    <email>mercury@example.com</email>
  </record>
  <record type="location">
    <uid>gemini</uid>
    <short-name>gemini</short-name>
    <password>gemini</password>
    <full-name>Gemini Twelve</full-name>
    <email>gemini@example.com</email>
  </record>
  <record type="location">
    <uid>apollo</uid>
    <short-name>apollo</short-name>
    <password>apollo</password>
    <full-name>Apollo Eleven</full-name>
    <email>apollo@example.com</email>
  </record>
  <record type="location">
    <uid>orion</uid>
    <short-name>orion</short-name>
    <password>orion</password>
    <full-name>Orion</full-name>
    <email>orion@example.com</email>
  </record>
  <record type="resource">
    <uid>transporter</uid>
    <short-name>transporter</short-name>
    <password>transporter</password>
    <full-name>Mass Transporter</full-name>
    <email>transporter@example.com</email>
  </record>
  <record type="resource">
    <uid>ftlcpu</uid>
    <short-name>ftlcpu</short-name>
    <password>ftlcpu</password>
    <full-name>Faster-Than-Light Microprocessor</full-name>
    <email>ftlcpu@example.com</email>
  </record>
  <record type="resource">
    <uid>non_calendar_proxy</uid>
    <short-name>non_calendar_proxy</short-name>
    <password>non_calendar_proxy</password>
    <full-name>Non-calendar proxy</full-name>
    <email>non_calendar_proxy@example.com</email>
  </record>
  <record type="resource">
    <uid>disabled</uid>
    <short-name>disabled</short-name>
    <password>disabled</password>
    <full-name>Disabled Record</full-name>
    <email>disabled@example.com</email>
  </record>
  <record type="location">
    <uid>__sanchezoffice__</uid>
    <short-name>sanchezoffice</short-name>
    <full-name>Sanchez Office</full-name>
  </record>
  <record type="location">
    <short-name>location01</short-name>
    <uid>75EA36BE-F71B-40F9-81F9-CF59BF40CA8F</uid>
    <guid>75EA36BE-F71B-40F9-81F9-CF59BF40CA8F</guid>
    <password>location01</password>
    <full-name>Room 01</full-name>
  </record>
  <record type="location">
    <short-name>room-with-address-1</short-name>
    <uid>room-addr-1</uid>
    <guid>634A102B-6902-464F-9451-8A86A31628C1</guid>
    <password>room-addr-2</password>
    <full-name>Room with Address 1</full-name>
    <associated-address>1-infinite-loop</associated-address>
  </record>
  <record type="location">
    <short-name>room-with-address-2</short-name>
    <uid>room-addr-2</uid>
    <password>room-addr-2</password>
    <full-name>Room with Address 2</full-name>
    <associated-address>2-infinite-loop</associated-address>
  </record>
  <record type="address">
    <short-name>il1</short-name>
    <uid>1-infinite-loop</uid>
    <full-name>One Infinite Loop</full-name>
    <street-address>1 Infinite Loop, Cupertino, CA 95014</street-address>
    <geographic-location>37.331741,-122.030333</geographic-location>
  </record>
  <record type="address">
    <short-name>il2</short-name>
    <uid>2-infinite-loop</uid>
    <full-name>Two Infinite Loop</full-name>
    <street-address>2 Infinite Loop, Cupertino, CA 95014</street-address>
    <geographic-location>37.332633,-122.030502</geographic-location>
  </record>

</directory>
