=== apple/ccs-calendarserver/conf/auth/augments.dtd
<!--
Copyright (c) 2009-2014 Apple Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

<!ELEMENT augments (record*) >

  <!ELEMENT record (
  		uid,
  		enable,
  		(server-id, partition-id?)?,
  		enable-calendar?,
  		enable-addressbook?,
  		enable-login?,
  		auto-schedule?,
  		auto-schedule-mode?,
  		auto-accept-group?
  )>
    <!ATTLIST record repeat CDATA "1">

  <!ELEMENT uid                (#PCDATA)>
  <!ELEMENT enable             (#PCDATA)>
  <!ELEMENT server-id          (#PCDATA)>
  <!ELEMENT partition-id       (#PCDATA)>
  <!ELEMENT enable-calendar    (#PCDATA)>
  <!ELEMENT enable-addressbook (#PCDATA)>
  <!ELEMENT enable-login       (#PCDATA)>
  <!ELEMENT auto-schedule      (#PCDATA)>
  <!ELEMENT auto-schedule-mode (#PCDATA)>
  <!ELEMENT auto-accept-group  (#PCDATA)>
>

=== apple/ccs-calendarserver/twistedcaldav/directory/test/augments-test-default.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
Copyright (c) 2009-2010 Apple Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 -->

<!DOCTYPE accounts SYSTEM "../../../conf/auth/augments.dtd">

<augments>
  <record>
    <uid>Default</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>true</enable-addressbook>
    <partition-id>00001</partition-id>
  </record>
  <record>
    <uid>Location-Default</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
    <partition-id>00004</partition-id>
    <auto-schedule>true</auto-schedule>
  </record>
  <record>
    <uid>Location-AA*</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
    <partition-id>00005</partition-id>
    <auto-schedule>true</auto-schedule>
  </record>
  <record>
    <uid>Resource-Default</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
    <partition-id>00006</partition-id>
    <auto-schedule>true</auto-schedule>
  </record>
  <record>
    <uid>Resource-AA*</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
    <partition-id>00007</partition-id>
    <auto-schedule>true</auto-schedule>
  </record>
  <record>
    <uid>AA*</uid>
    <enable>true</enable>
    <partition-id>00001</partition-id>
  </record>
  <record>
    <uid>AB*</uid>
    <enable>false</enable>
  </record>
  <record>
    <uid>B*</uid>
    <enable>true</enable>
    <partition-id>00002</partition-id>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>true</enable-addressbook>
  </record>
  <record>
    <uid>C*</uid>
    <enable>true</enable>
    <partition-id>00003</partition-id>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>true</enable-addressbook>
    <auto-schedule>true</auto-schedule>
  </record>
  <record>
    <uid>D11F03A0-97EA-48AF-9A6C-FAC7F3975766</uid>
    <enable>true</enable>
  </record>
  <record>
    <uid>6423F94A-6B76-4A3A-815B-D52CFD77935D</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>true</enable-addressbook>
  </record>
  <record>
    <uid>5A985493-EE2C-4665-94CF-4DFEA3A89500</uid>
    <enable>false</enable>
  </record>
  <record>
    <uid>8B4288F6-CC82-491D-8EF9-642EF4F3E7D0</uid>
    <enable>true</enable>
    <enable-calendar>false</enable-calendar>
    <enable-addressbook>false</enable-addressbook>
  </record>
  <record>
    <uid>5FF60DAD-0BDE-4508-8C77-15F0CA5C8DD1</uid>
    <enable>true</enable>
    <partition-id>00001</partition-id>
  </record>
  <record>
    <uid>543D28BA-F74F-4D5F-9243-B3E3A61171E5</uid>
    <enable>true</enable>
    <partition-id>00002</partition-id>
  </record>
  <record>
    <uid>6A73326A-F781-47E7-A9F8-AF47364D4152</uid>
    <enable>true</enable>
    <partition-id>00002</partition-id>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>true</enable-addressbook>
    <auto-schedule>true</auto-schedule>
  </record>
  <record>
    <uid>FC674703-8008-4A77-B80E-0DB55A9CE620</uid>
    <enable-login>false</enable-login>
  </record>
  <record>
    <uid>B473DC32-1B0D-45EE-9BAC-DA878AE9CE74</uid>
    <enable-login>true</enable-login>
  </record>
  <record>
    <uid>9F2B176D-B3F5-483A-AA63-0A1FC6E6D54B</uid>
  </record>
</augments>

=== apple/ccs-calendarserver/twistedcaldav/directory/test/augments-test.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
Copyright (c) 2009-2014 Apple Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 -->

<!DOCTYPE accounts SYSTEM "../../../conf/auth/augments.dtd">

<augments>
  <record>
    <uid>D11F03A0-97EA-48AF-9A6C-FAC7F3975766</uid>
  </record>
  <record>
    <uid>6423F94A-6B76-4A3A-815B-D52CFD77935D</uid>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>true</enable-addressbook>
  </record>
  <record>
    <uid>5A985493-EE2C-4665-94CF-4DFEA3A89500</uid>
  </record>
  <record>
    <uid>8B4288F6-CC82-491D-8EF9-642EF4F3E7D0</uid>
    <enable-calendar>false</enable-calendar>
    <enable-addressbook>false</enable-addressbook>
  </record>
  <record>
    <uid>5FF60DAD-0BDE-4508-8C77-15F0CA5C8DD1</uid>
  </record>
  <record>
    <uid>543D28BA-F74F-4D5F-9243-B3E3A61171E5</uid>
  </record>
  <record>
    <uid>6A73326A-F781-47E7-A9F8-AF47364D4152</uid>
    <server-id>00002</server-id>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>true</enable-addressbook>
    <auto-schedule-mode>automatic</auto-schedule-mode>
  </record>
  <record>
    <uid>C5BAADEE-6B35-4FD5-A98A-5DF6BBAAC47A</uid>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>true</enable-addressbook>
    <auto-schedule-mode>automatic</auto-schedule-mode>
  </record>
  <record>
    <uid>8AB34DF9-0297-4BA3-AADB-DB557DDD21E7</uid>
    <enable-calendar>true</enable-calendar>
    <enable-addressbook>true</enable-addressbook>
    <auto-schedule-mode>accept-always</auto-schedule-mode>
  </record>
  <record>
    <uid>FC674703-8008-4A77-B80E-0DB55A9CE620</uid>
    <enable-login>false</enable-login>
  </record>
  <record>
    <uid>B473DC32-1B0D-45EE-9BAC-DA878AE9CE74</uid>
    <enable-login>true</enable-login>
  </record>
  <record>
    <uid>9F2B176D-B3F5-483A-AA63-0A1FC6E6D54B</uid>
  </record>
</augments>

=== apple/ccs-calendarserver/calendarserver/tools/test/deprovision/augments.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
Copyright (c) 2009-2014 Apple Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 -->

<!DOCTYPE accounts SYSTEM "../../../conf/auth/augments.dtd">

<augments>
  <record>
    <uid>E9E78C86-4829-4520-A35D-70DDADAB2092</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
  </record>
  <record>
    <uid>291C2C29-B663-4342-8EA1-A055E6A04D65</uid>
    <enable>true</enable>
    <enable-calendar>true</enable-calendar>
  </record>
</augments>
